# -*- coding: utf-8 -*-
"""Zaid umar.lab1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aRtBqe7_gWSQF3El7hD5WRmTltgUksJt
"""

print("--- Simple Travel Agent ---\n")


place1 = "Karachi"
cost1 = 8000
travel_car1 = 0
travel_plane1 = 0

place2 = "Lahore"
cost2 = 10000
travel_car2 = 8000
travel_plane2 = 25000

place3 = "Murree"
cost3 = 12000
travel_car3 = 12000
travel_plane3 = 30000


budget = int(input("Enter your total budget in Rupees: "))
days = int(input("How many days is the trip: "))
conveyance = input("Conveyance? Enter 'car' or 'plane': ").lower()


stay1 = cost1 * days
stay2 = cost2 * days
stay3 = cost3 * days


if conveyance == "car":
    total1 = stay1 + travel_car1
    total2 = stay2 + travel_car2
    total3 = stay3 + travel_car3
elif conveyance == "plane":
    total1 = stay1 + travel_plane1
    total2 = stay2 + travel_plane2
    total3 = stay3 + travel_plane3
else:
    print("Invalid conveyance. Please enter 'car' or 'plane'.")
    exit()

print(f"\n--- Options for you using {conveyance} ---\n")


found = False

if budget >= total1:
    print(f"1. {place1} - Total cost for {days} days: {total1} Rupees")
    found = True

if budget >= total2:
    print(f"2. {place2} - Total cost for {days} days: {total2} Rupees")
    found = True

if budget >= total3:
    print(f"3. {place3} - Total cost for {days} days: {total3} Rupees")
    found = True


if not found:
    print("Sorry, trip is not possible with your budget.")
    min_cost = min(total1, total2, total3)
    print(f"Minimum cost is: {min_cost} Rupees. Please increase your budget.")